### PR TITLE
Add ESP32 support.

### PR DESCRIPTION
**Pull request by bestpika**

### CODE REVIEW

**Comment by jburhenn** [comment]
Great! Thanks for your contribution. Did you test this with a particular ESP32 device? If so, which one? We can add some compatibility info to the readme for the particular device.

Also, did you use the Arduino IDE when building? Did you have to go through a particular process to get ESP32 builds working for the Arduino IDE? If so, would you be able to provide some comments at the top of the ESP32.ino example file that other users could follow to get it set up and working? Thanks.

**Comment by bestpika** [comment]
I test IntoRobot Fig and NodeMCU-32s.
And I use Arduino IDE to build.
I never change any setting and work fine.

**Comment by trungkiendt9** [comment]
It working with ESP32.  Thanks. @bestpika. 
I use PlatformIO IDE and ESP32 Dev Board.

**Comment by Bernard26** [comment]
Hi 
I have made changes but I get  **[51] WiFi shield not present**
Thank you

**Comment by jburhenn** [comment]
@Bernard26 That error happens when it can't detect the WiFi on the device. Have you selected the correct board when trying to compile? If so, you might try making a post on the [community](http://community.mydevices.com) with your particular board info see if anyone else has seen the same problem.

**Comment by Bernard26** [comment]
Hello,
@**jburhenn** .. Thank you for replying.
My board comes from China  HW-607 with CH340G and **ESP32 dev module** selected .
It compiles .. I wil post my problem on Cayenne community.
Salutations.

**Comment by Bernard26** [comment]
Hi,
All is OK  ... just add  **#include<WiFi.h>** and **WiFi.begin(ssid, password)**;
Thank you :)

**Pull request merged**
